[workspace]
authors = ["Egor Lappo <elappo@stanford.edu>"]
channels = ["conda-forge", "bioconda"]
name = "coalescent-psi"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.2.5,<3"
matplotlib = ">=3.10.3,<4"
scipy = ">=1.15.2,<2"
muscle = ">=5.3,<6"
ipykernel = ">=6.29.5,<7"
seaborn = ">=0.13.2,<0.14"
biopython = ">=1.85,<2"
requests = ">=2.32.3,<3"
tqdm = ">=4.67.1,<5"
polars = ">=1.29.0,<2"
